AllCops:
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'Gemfile*'
    - 'bin/**/*'
    - 'test/**/*'
    - 'Rakefile'

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false
